rapid7/armor

- armor-base/src/main/java/com/rapid7/armor/io/FixedCapacityByteBufferPool.java
- armor-write/src/main/java/com/rapid7/armor/store/FileWriteStore.java
- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/store/WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/write/component/RowGroupWriter.java
- armor-write/src/test/java/com/rapid7/armor/FileStoreTest.java
- armor-write/src/test/java/com/rapid7/armor/FileStoreV2Test.java
- armor-write/src/test/java/com/rapid7/armor/S3StoreTest.java
> Expand tests

- armor-base/src/main/java/com/rapid7/armor/interval/Interval.java
- armor-base/src/main/java/com/rapid7/armor/interval/IntervalStrategy.java
- armor-base/src/main/java/com/rapid7/armor/interval/IntervalStrategyFixed.java
- armor-base/src/main/java/com/rapid7/armor/interval/IntervalStrategyMonthly.java
- armor-base/src/main/java/com/rapid7/armor/interval/IntervalStrategySingle.java
- armor-base/src/main/java/com/rapid7/armor/interval/IntervalStrategyYearly.java
- armor-base/src/main/java/com/rapid7/armor/meta/ColumnMetadata.java
- armor-write/src/main/java/com/rapid7/armor/store/FileWriteStore.java
- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/store/WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ArmorWriter.java
added support for copying interval slices
Manual
> added support for copying interval slices

- armor-base/src/main/java/com/rapid7/armor/meta/ShardMetadata.java
- armor-base/src/main/java/com/rapid7/armor/schema/ColumnId.java
- armor-base/src/main/java/com/rapid7/armor/schema/DiffTableName.java
- armor-base/src/main/java/com/rapid7/armor/shard/ColumnShardId.java
- armor-base/src/main/java/com/rapid7/armor/shard/ShardId.java
- armor-read/src/main/java/com/rapid7/armor/read/fast/FastArmorShardColumn.java
- armor-write/src/main/java/com/rapid7/armor/store/FileWriteStore.java
- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/store/WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/write/component/EntityIndexWriter.java
- armor-write/src/main/java/com/rapid7/armor/write/component/RowGroupWriter.java
- armor-write/src/main/java/com/rapid7/armor/write/diff/writers/ColumnShardDiffWriter.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ArmorWriter.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ColumnFileWriter.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/IShardWriter.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ShardWriter.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/TableWriter.java
- armor-write/src/test/java/com/rapid7/armor/FileStoreV2Test.java
> Diff based writes

- armor-write/src/main/java/com/rapid7/armor/write/writers/ArmorWriter.java
- armor-write/src/test/java/com/rapid7/armor/FileStoreV2Test.java
> Fix delete diff

- armor-base/src/main/java/com/rapid7/armor/store/StoreConstants.java
- armor-read/src/main/java/com/rapid7/armor/store/S3ReadStore.java
- armor-write/pom.xml
- armor-write/src/main/java/com/rapid7/armor/store/FileWriteStore.java
- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/store/WriteStore.java
- armor-write/src/test/java/com/rapid7/armor/S3StoreTest.java
> add caching of tenants

- armor-read/src/main/java/com/rapid7/armor/store/S3ReadStore.java
- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/store/WriteStore.java
> updated retrieval of tenants to fall back to a non cached version if the cache is empty

- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
- armor-write/src/test/java/com/rapid7/armor/S3StoreTest.java
> added retry logic for copy of current shard

- armor-write/src/test/java/com/rapid7/armor/S3StoreTest.java
> added clearing of bucket before each test in S3StoreTest

- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
> added fallback logic when listing tenants in S3WriteStore

- armor-write/src/main/java/com/rapid7/armor/store/FileWriteStore.java
- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
> Fix potential for duplicate columns to be saved.

- armor-write/src/test/java/com/rapid7/armor/FileStoreV2Test.java
> Don't fail test because unable to remove temp directory

- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
- armor-write/src/test/java/com/rapid7/armor/FileStoreV2Test.java
> Alter way captures are done

- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ArmorWriter.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ShardWriter.java
> Update capture writes

- armor-base/src/main/java/com/rapid7/armor/xact/DistXactRecord.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ArmorWriter.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ShardWriter.java
> Shard commit

- armor-write/src/test/java/com/rapid7/armor/FileWriteStoreTest.java
> Minor update

- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ArmorWriter.java
> Add mdc support for shard and xact

- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ArmorWriter.java
> Add NPE check for null entity id

- armor-write/src/main/java/com/rapid7/armor/write/writers/ArmorWriter.java
> Apply fix to resolve entity id column

- armor-write/src/main/java/com/rapid7/armor/write/writers/ArmorWriter.java
> Compact always

- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
> Fix cache issue

- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
> More caching fixes

- armor-base/src/main/java/com/rapid7/armor/entity/Entity.java
- armor-base/src/main/java/com/rapid7/armor/schema/DataType.java
- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ArmorWriter.java
- armor-write/src/main/java/com/rapid7/armor/write/writers/ShardWriter.java
- armor-write/src/test/java/com/rapid7/armor/FileStoreV2Test.java
- armor-write/src/test/java/com/rapid7/armor/FileWriteStoreTest.java
- armor-write/src/test/java/com/rapid7/armor/S3StoreTest.java
> Change the delete api

- armor-write/src/main/java/com/rapid7/armor/store/S3WriteStore.java
> Log all s3 errors in write store
